name: Generate GitHub Stats

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Overview Stats
        uses: lowlighter/metrics@latest
        with:
          filename: github-stats/overview.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: iMoloy
          template: classic
          config_theme: tokyonight
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: iMoloy
          outputs: |
            github-stats/github-user-contribution-grid-snake.svg
            github-stats/github-user-contribution-grid-snake-dark.svg?palette=github-dark


